# Generated by Django 3.2.25 on 2024-04-07 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='atm_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('card_no', models.CharField(max_length=200)),
                ('cvv', models.CharField(max_length=200)),
                ('exp_date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=200)),
                ('ifsc', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('image', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('account_no', models.CharField(max_length=200)),
                ('amount', models.CharField(default=0, max_length=200)),
                ('BRANCH', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Secure_ATM_app.branch')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('usertype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Secure_ATM_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='feedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('feedback', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Secure_ATM_app.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Secure_ATM_app.login'),
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('complaint', models.CharField(max_length=200)),
                ('reply', models.CharField(max_length=200)),
                ('reply_date', models.CharField(max_length=200)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Secure_ATM_app.customer')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Secure_ATM_app.login'),
        ),
        migrations.CreateModel(
            name='block_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(default='', max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('image', models.CharField(default='', max_length=200)),
                ('ATM_CARD', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Secure_ATM_app.atm_card')),
            ],
        ),
        migrations.CreateModel(
            name='authorized_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Secure_ATM_app.customer')),
            ],
        ),
        migrations.AddField(
            model_name='atm_card',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Secure_ATM_app.customer'),
        ),
    ]
